version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "lib/QECCore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
