name = "QuantumClifford"
uuid = "0525e862-1e90-11e9-3e4d-1b39d7109de1"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]
version = "0.2.11"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ILog2 = "2cd5bd5f-40a1-5050-9e10-fc8cdb6109f5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Quantikz = "b0d11df0-eea3-4d79-b4a5-421488cbf74b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Combinatorics = "1.0"
DocStringExtensions = "0.8"
ILog2 = "0.2"
LoopVectorization = "0.12"
Polyester = "0.5.4"
Quantikz = "1.1.2"
RecipesBase = "0.7, 0.8, 1.0"
Requires = "1.1"
StatsBase = "0.33"
julia = "1.5"
